{{- with .Values.extraSecrets }}
  {{- range $_, $values := . }}
---
  {{- if $.Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "extraSecret name is required!" .name }}
  labels:
{{ include "app.labels" $ | indent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .values}}
  {{ $key }}: {{ $value | quote }}
{{- end}}
  {{- end }}
  {{- end }}
{{- end }}
