{{- with .Values.secret }}
  {{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" $ }}
  labels:
{{ include "app.labels" $ | indent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .values}}
  {{ $key }}: {{ $value | quote }}
{{- end}}
  {{- end }}
{{- end }}
