FROM node:12 AS stage-one

# Install DEB dependencies and others.
RUN \
	set -x \
	&& apt-get autoremove \
	&& apt-get clean \
	&& apt-get update \
	&& apt-get install -y net-tools build-essential valgrind

WORKDIR /service

COPY save-config-and-run.sh .
COPY git-hash.json .
COPY package.json .
COPY lib lib
RUN npm install
COPY certs certs

EXPOSE 443
CMD ["bash", "/service/save-config-and-run.sh"]