#!/bin/bash
export LANG=C.UTF-8
echo "${GOOGLE_APPLICATION_CREDENTIAL_CONTENTS//'\n'/\\n}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
# iconv -f ascii -t utf-8 "${GOOGLE_APPLICATION_CREDENTIALS}.tmp" > "$GOOGLE_APPLICATION_CREDENTIALS"
# cat $GOOGLE_APPLICATION_CREDENTIALS
# ls -l $GOOGLE_APPLICATION_CREDENTIALS
# file -i *
node /service/lib/server.js
