appName: nonexistant
appVersion: 0.0.0
appSystemName: nonexistant

configmap:
  data:
    APP_CONFIG: nonexistant

deployment:
  appDockerRepo: nonexistant
  resources:
    requests:
      memory: 0Mi
      cpu: 0m
    limits:
      memory: 0Mi
      cpu: 0m
  extraContainers:
    - name: my-sidecar
      image: sidecar:latest
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      envFrom:
        - configMapRef:
          name: my-sidecar
        - secretRef:
          name: my-sidecar
      volumeMounts:
        - name: sidecar-mount
          mountPath: /srv/var/lib/sidecar-lib

extraConfigmaps:
  - name: my-sidecar
    data:
      SIDECAR_CONFIG: sidecar-config

extraSecrets:
  - name: my-sidecar
    values:
      SIDECAR_KEY: sidecar-key

ingress:
  enabled: true
  port: http
  tlsEnabled: false
  annotations:
    kubernetes.io/ingress.class: nginx

secret:
  enabled: true
  values:
    SECRET_KEY: key

service:
  portsByName:
    http: 8080
